---
title: "Chapter 4 - Principal Component Analysis"
output: html_document
date: "2024-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, message=FALSE}
# Import libraries and data set
library(tidyverse) # data cleaning and processing
library(factoextra) # clustering and PCA (fviz)
library(ggrepel) # text on charts
library(gridExtra) # display multiple charts in a grid (grid.arrange)
library(kableExtra) # pretty tables (kbl, kable_classic_2)
library(psych) # factor analysis (fa.diagram)
library(ggpubr) # outlining clusters (ggscatter)
library(RColorBrewer) # color palettes
library(wesanderson) # more color palettes

raw <- read_table("dataset3.txt")
```

```{r, warning=FALSE, message=FALSE}
### Select variables and clean the data
raw1 <- raw |>
  select(ProdName, 8, 9, 10, 26, 27, 28) |>
  rename(x1=2, x2=3, x3=4, x4=5, x5=6, x6=7) |>
  column_to_rownames(var="ProdName") 

### Scale the data set
df <- raw1 |>
  scale()
```


```{r}
### Box plots of scaled data
df |>
  as_tibble() |>
  pivot_longer(cols = 1:6, names_to = "variable", values_to = "value") |>
  ggplot(aes(x = variable, y = value)) +
  geom_boxplot() + theme_bw() + ggtitle("Standardized Process Variables")
```


```{r}
### Correlation matrix
df |> cor()
```

```{r}
### Summary
df |> summary()
```


```{r}
### k-means clustering
set.seed(123) # for reproducibility
fviz_nbclust(df, kmeans, method = "wss")
```

```{r}
### Visualizing clusters
set.seed(123) # for reproducibility
k3 <- kmeans(df, centers = 3, nstart = 25)
k4 <- kmeans(df, centers = 4, nstart = 25)
k5 <- kmeans(df, centers = 5, nstart = 25)
k6 <- kmeans(df, centers = 6, nstart = 25)

### plots to compare cluster options
p1 <- fviz_cluster(k3, geom = "point",  data = df) + ggtitle("k = 3") + theme_bw()
p2 <- fviz_cluster(k4, geom = "point",  data = df) + ggtitle("k = 4") + theme_bw()
p3 <- fviz_cluster(k5, geom = "point",  data = df) + ggtitle("k = 5") + theme_bw()
p4 <- fviz_cluster(k6, geom = "point", data = df) + ggtitle("k = 6") + theme_bw()

grid.arrange(p1, p2, p3, p4, nrow = 2)
```

```{r}
### selected cluster summary
k4
```


```{r}
### Cluster Visualization on PC's
fviz_cluster(k4, geom = "point", data = df) + 
  theme_bw() + labs(y= "PC1", x = "PC2")  + ylim(-3,4) +
  geom_text_repel(aes(label = rownames(df)), 
                  max.overlaps = 23, size = 3) + 
  ggtitle("Principal Components with Clusters")
```


```{r}
### Cluster visualization on two variables

clusters <- names(k4$cluster) |> 
  as_tibble() |>
  mutate(cluster = k4$cluster) |>
  rename(ProdName = value)

df_tibble <- df |>
  as_tibble() |>
  mutate(ProdName = row.names(df))

df1 <- left_join(clusters, df_tibble, by = join_by(ProdName))

g12 <-  ggplot(df1, aes(x1, x2, color = factor(cluster), label = ProdName)) +
  geom_point()  + theme_bw() + ylim(-2,4)
g13 <-  ggplot(df1, aes(x1, x3, color = factor(cluster), label = ProdName)) +
  geom_point() + theme_bw() + ylim(-2,4)
g14 <-  ggplot(df1, aes(x1, x4, color = factor(cluster), label = ProdName)) +
  geom_point() + theme_bw() + ylim(-2,4)
g15 <-  ggplot(df1, aes(x1, x5, color = factor(cluster), label = ProdName)) +
  geom_point() + theme_bw() + ylim(-2,4)
g16 <-  ggplot(df1, aes(x1, x6, color = factor(cluster), label = ProdName)) +
  geom_point() + theme_bw() + ylim(-2,4)

grid.arrange(g12, g13, g14, g15, g16, nrow = 3)
```

```{r}
### Cluster list
df1 |>
  select(ProdName, cluster) |>
  rename("Product" = ProdName,
         "Cluster" = cluster) |>
  arrange(Cluster) |>
  kbl() |>
  kable_classic_2(full_width = F)
```



```{r}
### Principal component analysis results and summary
pca_result <- prcomp(raw1, scale.=TRUE)

pca_result
summary(pca_result)
```


```{r}
# Scree plot to visualize the importance of components
fviz_eig(pca_result, addlabels = TRUE) + theme_bw()
```

```{r echo=FALSE}
# Interpretation of Selected PCs
loadings <- pca_result$rotation 
loadings[,1:2] |>
  round(2) |>
  kbl() |>
  kable_classic_2(full_width = F)
```


```{r}
### PC Results With Clusters
pca_x_tib <- pca_result$x[,1:2] |> 
  as_tibble() |>
  mutate(ProdName = rownames(pca_result$x)) |>
  left_join(clusters, by = join_by(ProdName)) |>
  mutate(ProdName = factor(ProdName),
         cluster = factor(cluster))

pca_x_tib |>
  ggplot(aes(x = PC1, y = PC2, color = cluster)) +
  geom_point() + theme_bw() + ggtitle("PC1 vs PC2 From prcomp Function")
```

```{r}
pca_x_tib |>
  ggscatter(x = "PC1", y = "PC2", color = "cluster", palette ="Dark2",  ellipse = TRUE, ellipse.type = "convex",
            legend = "right", ggtheme = theme_bw()) +   ylim(c(-3,4)) +
  geom_text_repel(aes(label = rownames(df)), max.overlaps = 23, size = 3) + 
  ggtitle("Principal Components With Clusters")
```





